name: 自动更新配件价格
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: python update_prices.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: "自动更新 p:价格"
